name: Testes Selenium Simples

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Chrome
        run: |
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install Flask selenium pytest webdriver-manager pytest-html

      - name: Verify installations
        run: |
          python --version
          google-chrome --version
          python -c "import selenium; print('Selenium OK')"
          python -c "import flask; print('Flask OK')"

      - name: Create directories
        run: mkdir -p reports screenshots logs

      - name: Start Flask app
        run: |
          python app.py &
          sleep 10
          curl http://127.0.0.1:5001/ || exit 1

      - name: Run basic test
        run: |
          pytest tests/test_navigation.py::TestNavigation::test_navigate_to_home_page -v --browser=chrome --headless

      - name: Run all tests
        run: |
          pytest -v --browser=chrome --headless --html=reports/report.html --self-contained-html
        continue-on-error: true

      - name: Upload results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            reports/
            screenshots/
