name: Testes Selenium - Simples

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar dependências do sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            google-chrome-stable \
            xvfb

      - name: Instalar dependências Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Criar diretórios necessários
        run: |
          mkdir -p reports screenshots logs

      - name: Verificar instalação do Chrome
        run: |
          google-chrome --version
          which google-chrome

      - name: Iniciar aplicação Flask
        run: |
          python app.py &
          sleep 10
          # Verificar se a aplicação respondeu
          curl -f http://127.0.0.1:5001/ || (echo "Aplicação Flask não iniciou" && exit 1)

      - name: Executar testes básicos
        run: |
          pytest tests/test_navigation.py -v --browser=chrome --headless --html=reports/basic-report.html --self-contained-html
        env:
          DISPLAY: :99

      - name: Executar todos os testes (se básicos passaram)
        if: success()
        run: |
          pytest -v --browser=chrome --headless --html=reports/full-report.html --self-contained-html --tb=short
        env:
          DISPLAY: :99
        continue-on-error: true

      - name: Upload relatórios
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-reports
          path: |
            reports/
            screenshots/
            logs/

      - name: Upload screenshots de falhas
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: failure-screenshots
          path: screenshots/
